### ISSUE TITLE
Attachments that are too large do not notify user of errors

### ISSUE THREAD

**Issue by modelm** [r-a-y/bp-rbe-inbound-forum-attachments#4]
I noticed when I try to attach an image that exceeds the size limit, the attachment is not posted (but the reply body is) and I don't get any notification of an error by email or other means.

I do see the error in the bp-rbe-debug.log: `[03-Jan-2018 15:01:55] Message #: Attachment error - could not add attachment "sphericalcowtransform.gif" because it is too large.`

I have also gotten error notification email responses when my reply could not be posted for other reasons.

I think it would make sense to leverage the same mechanism to notify users their file could not be uploaded for whatever reason. Does this all make sense and am I missing anything? I'm happy to work on adding this if you like, just wanted to make sure I take the right approach.

**Comment by r-a-y** [comment]
This is a bug.  Thanks for finding it!

Just fixed this upstream in RBE.  Pull the latest changes to test.

**Comment by modelm** [comment]
Great news! I was just about to reply and say I do get notified if there are other valid attachments, but I can also confirm I get notified of single attachments with the latest version. Thanks!
